apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptreatment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: IPTreatment
  template:
    metadata:
      labels:
        app: IPTreatment
    spec:
      containers:
      - name: iptreatmentrepos
        image: iptreatmentmanagement3cr.azurecr.io/iptreatmentrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: iptreatmentsn

---
apiVersion: v1
kind: Service
metadata:
  name: iptreatment
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: IPTreatment